Tried to fix issue #173 (using prec2posix.h in MariaDB)
PCRE2Project/pcre2 pull request #174
Opened 2022-12-08 10:36 UTC by cbouc

#173 Added default (empty) definition for PCRE2_CALL_CONVENTION in prec2posix.h just like  that in prec2.h

2022-12-08 18:31 UTC, carenas requested changes

2022-12-08 18:31 UTC, carenas commented on src/pcre2posix.h
> +
the equivalent code should be then removed from pcre2posix.c

2022-12-09 09:32 UTC, PhilipHazel commented
Unfortunately, this issue was not caught by the tests because pcre2test includes both pcre2.h and pcre2posix.h. I will do two things: I will move the default definition (and its comment) from pcre2posix.c to pcre2posix.h and I will write a little test program that just includes pcre2posix.h (without pcre2.h) and add this test to the test suite.

2022-12-09 15:08 UTC, thesamesam commented
@PhilipHazel Once a test is added, would you consider a new release for this? Otherwise all distributors of pcre2 are likely to have to hit the problem and then backport the fix after hopefully stumbling upon the bug I filed.

2022-12-11 15:16 UTC, PhilipHazel commented
Fixed by 16802f39. I will put out a new release fairly soon.

2022-12-11 15:16 UTC, closed without merging