Add unsupported error code for jit
PCRE2Project/pcre2 pull request #213
Opened 2023-03-01 08:56 UTC by zherczeg

2023-03-01 10:17 UTC, minipli-oss requested changes
I'm just questioning myself if this change breaks existing applications because of the new error code? It did, at least, had an impact on the tests, so other projects might be impacted as well?

_/me goes looking..._

For example, GNU [grep](https://git.savannah.gnu.org/cgit/grep.git/tree/src/pcresearch.c?h=v3.8#n213) would be affected, as it explicitly tests the possible error codes:
```c
  ec = pcre2_jit_compile (pc->cre, PCRE2_JIT_COMPLETE);
  if (ec && ec != PCRE2_ERROR_JIT_BADOPTION && ec != PCRE2_ERROR_NOMEMORY)
    die (EXIT_TROUBLE, 0, _("JIT internal error: %d"), ec);
```
With your change it would `die()` on certain patterns instead of falling back to intepreter mode.

Judging by previous arguments made by yourself and @PhilipHazel in https://github.com/PCRE2Project/pcre2/pull/157, such an API-breaking change is stuff for a PCRE3 only.

2023-03-01 10:39 UTC, zherczeg commented
You are right, I need to read the documentation first:
https://www.pcre.org/current/doc/html/pcre2_jit_compile.html

"In particular, PCRE2_ERROR_JIT_BADOPTION is returned if JIT is not supported or if an unknown bit is set in options." - So I cannot change the badoption case (need to revert).

The code in git is simply wrong, they also did not read the documentation. In general we are talking about pcre2 api compatilbity, not bug compatibility with existing applications.

2023-03-01 10:53 UTC, minipli-oss commented
Ahh, saw your edit. So you meant `grep`, not `git`. Still, breaking `grep` won't be welcomed by many, I fear ;)

2023-03-01 11:24 UTC, carenas commented on src/pcre2_error.c
> +  "pattern does not supported by jit\0"
removing or using "is" instead of "does" would be a more appropriate phrase

2023-03-01 12:25 UTC, carenas commented
note some documentation might need updating as well.

the implications for this change from 7a233130adeedc0e37cd10a1b31ddafa8db6b65a, for example, is likely to require changes in users of this API.

2023-03-02 05:34 UTC, zherczeg commented
This patch is just exploring options. I have another idea: we could add flag to jit compile, which allows returning other error codes than nomemory / badoption. Will not make the code much more complex, and we have plenty of options. What do you think?

2023-03-02 17:48 UTC, PhilipHazel commented
I think it's a good idea to require a new option flag to enable the new return codes. That way there is no danger of breaking existing code, and applications can update in their own time if they want to make use of the new codes.

2023-04-16 06:04 UTC, carenas commented
> The code in grep is simply wrong, they also did not read the documentation. In general we are talking about pcre2 api compatilbity, not bug compatibility with existing applications.

FWIW GNU grep has been fixed

https://git.savannah.gnu.org/cgit/grep.git/commit/src/pcresearch.c?id=6e7253de1dd443be5f498078e1807ddfa4d364de

2024-07-23 07:01 UTC, closed without merging