Fix static MinGW build
PCRE2Project/pcre2 pull request #245
Opened 2023-05-06 10:39 UTC by rockdaboot

Fixes #243

2023-05-06 16:29 UTC, carenas commented on src/pcre2posix.h
> +setting in pcre2.h (which is included below); it defines only
>   (which is included below)

this is not correct in this context

2023-05-06 18:46 UTC, carenas requested changes
This breaks the non static build as shown by:

```
src/pcre2posix.c:62: warning: "PCRE2POSIX_EXP_DECL" redefined
   62 | #  define PCRE2POSIX_EXP_DECL extern __declspec(dllexport)
      | 
In file included from src/pcre2posix.c:52:
src/config.h:257: note: this is the location of the previous definition
  257 | #define PCRE2POSIX_EXP_DECL extern __attribute__ ((visibility ("default")))
      | 
src/pcre2posix.c:63: warning: "PCRE2POSIX_EXP_DEFN" redefined
   63 | #  define PCRE2POSIX_EXP_DEFN __declspec(dllexport)
      | 
src/config.h:260: note: this is the location of the previous definition
  260 | #define PCRE2POSIX_EXP_DEFN extern __attribute__ ((visibility ("default")))
      | 
```

2023-05-07 12:54 UTC, rockdaboot commented
> This breaks the non static build as shown by:
> 
> ```
> src/pcre2posix.c:62: warning: "PCRE2POSIX_EXP_DECL" redefined
>    62 | #  define PCRE2POSIX_EXP_DECL extern __declspec(dllexport)
>       | 
> In file included from src/pcre2posix.c:52:
> src/config.h:257: note: this is the location of the previous definition
>   257 | #define PCRE2POSIX_EXP_DECL extern __attribute__ ((visibility ("default")))
>       | 
> src/pcre2posix.c:63: warning: "PCRE2POSIX_EXP_DEFN" redefined
>    63 | #  define PCRE2POSIX_EXP_DEFN __declspec(dllexport)
>       | 
> src/config.h:260: note: this is the location of the previous definition
>   260 | #define PCRE2POSIX_EXP_DEFN extern __attribute__ ((visibility ("default")))
>       | 
> ```

This happens without this PR as well (commit 04fbb65b5e4931656d57de592c0e3ed89fe99b68).

2023-05-07 13:06 UTC, rockdaboot commented on src/pcre2posix.h
> +setting in pcre2.h (which is included below); it defines only
I amended the comment.

2023-05-07 13:13 UTC, rockdaboot commented
Removed the (superfluous) defines from `src/pcre2posix.c`.

2023-05-08 06:10 UTC, carenas commented
Those defines weren't superfluous; as explained in the documentation[1] the code you are adding is linking to, you need to set them differently depending of it you are building the library or not.

There is an interesting takeaway from your accidental solution though, and it is that the `__declspec(dllimport)` is actually optional, and that could be exploited (albeit with a small performance hit) to avoid having to keep track of the way the library was build with PCRE2_STATIC, and which is the root cause of the problem as shown in #246.

[1] https://web.archive.org/web/20130907051123/http://msdn.microsoft.com/en-us/library/y4h7bcy6(VS.80).aspx

2023-05-19 09:37 UTC, rockdaboot commented
Superceded by #249

2023-05-19 09:37 UTC, closed without merging