Test clang with and without optimisations
PCRE2Project/pcre2 pull request #559
Opened 2024-11-11 14:11 UTC by NWilson

2024-11-11 14:12 UTC, NWilson commented
The build failure here is due to #558

2024-11-12 09:09 UTC, carenas requested changes
it might be better to implement this test as part of another job that might also test other things in parallel that aren''t currently covered.

for example as part of a windows build that uses the alternative clang compiler that comes with Visual Studio and that might be updated in the future to build for ARM64

2024-11-15 11:28 UTC, NWilson commented on .github/workflows/dev.yml
> +        run: ./configure CC='clang' CFLAGS='${{ matrix.opt }} -fsanitize=undefined,address,integer -fno-sanitize-recover=undefined,integer -fno-sanitize=unsigned-integer-overflow,unsigned-shift-base,
Good point, done.

2024-11-15 12:24 UTC, zherczeg commented
Please update this patch to master.
After it is landed, the next step for me is #553

2024-11-15 12:46 UTC, NWilson commented
Grr, there's still a build problem, even after your fix. I'll try and work it out as quick as possible.

It may be that running `clang -fsanitize -O0` simply isn't sensible.

2024-11-15 12:48 UTC, carenas commented
> It may be that running `clang -fsanitize -O0` simply isn't sensible

yes, whichs is why I suggested doing it on windows instead (without. the sanitize part, of course)

2024-11-15 13:26 UTC, NWilson commented
@zherczeg I've fixed it; the next build should pass, and will be OK to merge.

2024-11-15 13:28 UTC, zherczeg commented
Ok. Lets wait the CI then.

2024-11-15 14:11 UTC, merged