Add coverage job
PCRE2Project/pcre2 pull request #571
Opened 2024-11-22 11:30 UTC by NWilson

2024-11-22 11:56 UTC, zherczeg commented
This looks useful.

`pcre2_jit_compile.c.html#L102: 58.9k #define MACHINE_STACK_SIZE 32768`

Interesting that a const has coverage. Some macros has coverage, others don't, so probably not all code is fully "covered" by the tool :)

2024-11-22 12:32 UTC, NWilson commented
I'd guess that constants which are built into the binary will be counted as "code" and generate coverage.

Macros which are only used by the preprocessor won't generate coverage. They have to actually write out some text which is seen as C code by the compiler.

I'd be interested in trying out the "Coveralls" or "CodeCov" services, which look like good ways to track coverage over time, coverage diff in a PR, and so on.

2024-11-22 14:44 UTC, carenas requested changes

2024-11-22 14:44 UTC, carenas commented on .github/workflows/build.yml
> +          if-no-files-found: error
missing "\n" at EOF

2024-11-22 17:17 UTC, NWilson commented on .github/workflows/build.yml
> +          if-no-files-found: error
Thanks! Fixed

2024-11-23 07:40 UTC, carenas approved these changes
it might be better to move this job into their own "tools.yml" in te long run, though

2024-11-23 08:59 UTC, merged

2024-11-25 10:35 UTC, NWilson commented
> it might be better to move this job into their own "tools.yml" in te long run, though

I feel like code-scanning tools (like CodeQL, or Clang Static Analyzer) should be in their own jobs.

However, code coverage should be part of the Release "Build" pipeline (not the "Dev" pipeline) because it's actually a fixed, reportable artifact of the release process: "we built the code; we ran the tests; the tests covered 85% of the code; now we release the binaries".